### ISSUE TITLE
Value and variable parameter

### ISSUE THREAD

**Issue by antonellocaroli** [bugy/script-server#491] opened 2021-09-11 04:43 UTC
Hi @bugy 

can you confirm that this does not work and there is no way to make it work?

```
"parameters": [
    {
      "name": "Select Iface",
      "param": "-a",
      "required": true,
      "type": "list",
      "default": {
        "script": "/script/rete/iface00.sh"
      },
      "values": {
        "script": "/script/rete/iface0.sh"
      },
      "description": "Select the network interface"
    },
    {
      "name": "Enable/Disable IP static",
      "param": "-f",
      "required": true,
      "type": "list",
      "default": {
        "script": "/script/rete/enadis.sh '${Select Iface}'"
      },
      "values": [
        "enable",
        "disable"
      ],
      "description": "Enable/Disable IP static - also shows the current status"
    },
```
/script/rete/iface00.sh  >  returns eth0
/script/rete/iface0.sh >  lists the network interfaces, ex. eth0 eth1 wlan0 etc

/script/rete/enadis.sh  eth0  > returns enable or disable

if I remember correctly the parameter in dafault doesn't work, right?

**Comment by bugy** [comment] 2021-09-11 06:57
Hi @antonellocaroli, you are right, this is not supported yet, here is a corresponding PR: https://github.com/bugy/script-server/pull/445

**Comment by bugy** [comment] 2021-09-11 06:57
And I think this ticket is a duplicate of #320 :sweat_smile:

**Comment by antonellocaroli** [comment] 2021-09-11 07:10
@bugy 
sorry, I had completely forgotten...
pardon :)

**Comment by bugy** [comment] 2021-09-11 07:12
No problem, it was created quite long ago already, easy to forget

antonellocaroli ***@***.***> schrieb am Sa., 11. Sept. 2021,
09:10:

**Closed** 2021-09-14 12:37 UTC
Labels: duplicate
